[project]
name = "homework-planner"
version = "0.1.0"
description = "Homework planner"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
api = [
    "fastapi>=0.118.0",
    "uvicorn>=0.37.0",
]
dev = [
    "mypy>=1.18.2",
    "pre-commit>=4.3.0",
    "ruff>=0.14.0",
]
